Add pygtrie to requirements
This caused a mean error in link_entities.py when using the
popular-entities linker:
AttributeError: 'NoneType' object has no attribute 'link_entities'
I suspect the reason for this is that the ModuleNotFoundError that must
have occured when calling set_forkserver_preload() was suppressed (just
as log messages are suppressed) but the linking_system could not be
loaded into the forks so linking_system was still None (from the initial
fake import statement).